LOCAL_PATH:= $(call my-dir)

# ========================================================
# switch_apr shared library
# ========================================================
include $(CLEAR_VARS)
LOCAL_SRC_FILES := \
	libs/libsndfile/src/sndfile.c \
	libs/libsndfile/src/common.c \
	libs/libsndfile/src/id3.c \
	libs/libsndfile/src/file_io.c \
	libs/libsndfile/src/command.c \
	libs/libsndfile/src/dither.c \
	libs/libsndfile/src/float32.c \
	libs/libsndfile/src/double64.c \
	libs/libsndfile/src/broadcast.c \
	libs/libsndfile/src/cart.c \
	libs/libsndfile/src/strings.c \
	libs/libsndfile/src/wav.c \
	libs/libsndfile/src/aiff.c \
	libs/libsndfile/src/au.c \
	libs/libsndfile/src/raw.c \
	libs/libsndfile/src/w64.c \
	libs/libsndfile/src/rf64.c \
	libs/libsndfile/src/paf.c \
	libs/libsndfile/src/svx.c \
	libs/libsndfile/src/nist.c \
	libs/libsndfile/src/ircam.c \
	libs/libsndfile/src/voc.c \
	libs/libsndfile/src/sds.c \
	libs/libsndfile/src/ogg.c \
	libs/libsndfile/src/txw.c \
	libs/libsndfile/src/wve.c \
	libs/libsndfile/src/dwd.c \
	libs/libsndfile/src/mat4.c \
	libs/libsndfile/src/mat5.c \
	libs/libsndfile/src/pvf.c \
	libs/libsndfile/src/xi.c \
	libs/libsndfile/src/htk.c \
	libs/libsndfile/src/sd2.c \
	libs/libsndfile/src/rx2.c \
	libs/libsndfile/src/avr.c \
	libs/libsndfile/src/flac.c \
	libs/libsndfile/src/caf.c \
	libs/libsndfile/src/mpc2k.c \
	libs/libsndfile/src/chunk.c \
	libs/libsndfile/src/wav_w64.c \
	libs/libsndfile/src/pcm.c \
	libs/libsndfile/src/ulaw.c \
	libs/libsndfile/src/alaw.c \
	libs/libsndfile/src/ima_adpcm.c \
	libs/libsndfile/src/ms_adpcm.c \
	libs/libsndfile/src/g72x.c \
	libs/libsndfile/src/gsm610.c \
	libs/libsndfile/src/chanmap.c \
	libs/libsndfile/src/dwvw.c \
	libs/libsndfile/src/vox_adpcm.c \
	libs/libsndfile/src/alac.c \
	libs/libsndfile/src/audio_detect.c \
	libs/libsndfile/src/G72x/g72x.c \
	libs/libsndfile/src/GSM610/gsm_create.c \
	libs/libsndfile/src/GSM610/gsm_option.c \
	libs/libsndfile/src/GSM610/gsm_destroy.c \
	libs/libsndfile/src/GSM610/gsm_encode.c \
	libs/libsndfile/src/GSM610/gsm_decode.c \
	libs/libsndfile/src/ima_oki_adpcm.c \
	libs/libsndfile/src/ALAC/ALACBitUtilities.c \
	libs/libsndfile/src/ALAC/alac_decoder.c \
	libs/libsndfile/src/ALAC/alac_encoder.c \
	libs/libsndfile/src/G72x/g723_16.c \
	libs/libsndfile/src/G72x/g723_24.c \
	libs/libsndfile/src/G72x/g721.c \
	libs/libsndfile/src/G72x/g723_40.c \
	libs/libsndfile/src/GSM610/code.c \
	libs/libsndfile/src/GSM610/decode.c \
	libs/libsndfile/src/ALAC/ag_dec.c \
	libs/libsndfile/src/ALAC/dp_dec.c \
	libs/libsndfile/src/ALAC/matrix_dec.c \
	libs/libsndfile/src/ALAC/matrix_enc.c \
	libs/libsndfile/src/ALAC/dp_enc.c \
	libs/libsndfile/src/ALAC/ag_enc.c \
	libs/libsndfile/src/GSM610/preprocess.c \
	libs/libsndfile/src/GSM610/lpc.c \
	libs/libsndfile/src/GSM610/short_term.c \
	libs/libsndfile/src/GSM610/long_term.c \
	libs/libsndfile/src/GSM610/rpe.c \
	libs/libsndfile/src/GSM610/add.c \
	libs/libsndfile/src/GSM610/table.c \ 

LOCAL_C_INCLUDES += \
					$(LOCAL_PATH)/libs/libsndfile/src \
					$(LOCAL_PATH)/src/include \
					$(LOCAL_PATH)/libs/spandsp/src \
					$(LOCAL_PATH)/libs/libteletone/src \
					$(LOCAL_PATH)/libs/tiff-4.0.2/libtiff \
					$(LOCAL_PATH)/libs/apr/include \
					$(LOCAL_PATH)/libs/apr-util/include \
					$(LOCAL_PATH)/libs/sofia-sip/libsofia-sip-ua/sdp \
					$(LOCAL_PATH)/libs/sofia-sip/libsofia-sip-ua/su \
					$(LOCAL_PATH)/libs/sofia-sip/open_c \
					$(LOCAL_PATH)/libs/libtpl-1.5/src \
					$(LOCAL_PATH)/libs/apr/include/arch/unix \
					$(LOCAL_PATH)/libs/apr/include/arch/unix \
					$(LOCAL_PATH)/libs/apr/random/unix \
					$(LOCAL_PATH)/libs/apr-util/include \
					$(LOCAL_PATH)/libs/apr-util/include/private \
					$(LOCAL_PATH)/../srtp/crypto/include/ \
					$(LOCAL_PATH)/../srtp/include \
					$(LOCAL_PATH)/../curl/include \
					$(LOCAL_PATH)/../sqlite/dist \
					$(LOCAL_PATH)/../openssl/include \
					$(LOCAL_PATH)/../speex/include \
					$(LOCAL_PATH)/../regex-re2 \
					$(LOCAL_PATH)/../regex-re2/util \
					$(LOCAL_PATH)/../libctb-0.16/include \
					$(LOCAL_PATH)/..//e2fsprogs/lib \
					$(LOCAL_PATH)/../jpeg \

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libsndfile

include $(BUILD_SHARED_LIBRARY)
