#define SIZEOF_UNSIGNED_SHORT_INT 2
#define SIZEOF_UNSIGNED_LONG_INT 4

#define HAVE_NETINET_IN_H 1
#define HAVE_UNISTD_H 1
#undef HAVE_MALLOC_H
#define HAVE_MALLOC_H 1
#define HAVE_GETOPT_LONG 1
#define VERSION "1.10"
